DO $$
DECLARE v_version_id TEXT;
BEGIN
  SELECT id INTO v_version_id FROM "BP_PF_v7pp_scoring_versions" 
  WHERE "modelId" = (SELECT id FROM "BP_PF_v7pp_scoring_models" WHERE code = 'PF_V7PP')
    AND status = 'PUBLISHED' ORDER BY "versionNumber" DESC LIMIT 1;

  INSERT INTO "BP_PF_v7pp_scoring_options" (id, "nodeId", code, label, value, score, "riskLevel", color, "orderIndex", "isDefault", "isActive", "metadataJson", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::TEXT, n.id, o.opt_code, o.opt_label, o.opt_score::TEXT, o.opt_score, o.opt_risk, o.opt_color, o.opt_order, false, true, o.opt_meta, NOW(), NOW()
  FROM (VALUES

  ('D1_SC1_SSC1', 'D1_SC1_SSC1_OPT1', 'Expérience très forte', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Sponsor ayant déjà réalisé plusieurs projets comparables avec succès dans le même secteur et dans des marchés similaires."}'),
  ('D1_SC1_SSC1', 'D1_SC1_SSC1_OPT2', 'Expérience solide', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Sponsor disposant d’une expérience sectorielle confirmée mais moins large ou sur des projets légèrement moins complexes."}'),
  ('D1_SC1_SSC1', 'D1_SC1_SSC1_OPT3', 'Expérience limitée', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Sponsor ayant une expérience partielle, dans un secteur proche ou avec un historique encore insuffisant."}'),
  ('D1_SC1_SSC1', 'D1_SC1_SSC1_OPT4', 'Aucune expérience pertinente', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Sponsor nouveau dans le secteur ou sans référence crédible en Project Finance."}'),
  ('D1_SC1_SSC2', 'D1_SC1_SSC2_OPT1', 'Track record excellent', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Historique de projets livrés et exploités dans les délais, budgets et performances attendues."}'),
  ('D1_SC1_SSC2', 'D1_SC1_SSC2_OPT2', 'Track record satisfaisant', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Historique globalement positif avec quelques écarts maîtrisés."}'),
  ('D1_SC1_SSC2', 'D1_SC1_SSC2_OPT3', 'Track record moyen', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Historique mitigé avec incidents significatifs mais récupérés."}'),
  ('D1_SC1_SSC2', 'D1_SC1_SSC2_OPT4', 'Track record faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Historique marqué par défauts, abandons, litiges ou incapacité à livrer."}'),
  ('D1_SC1_SSC3', 'D1_SC1_SSC3_OPT1', 'Très solide', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Sponsor dispose d’une capacité financière élevée pour soutenir le projet en cas de stress."}'),
  ('D1_SC1_SSC3', 'D1_SC1_SSC3_OPT2', 'Solide', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Sponsor financièrement sain mais non nécessairement investment grade."}'),
  ('D1_SC1_SSC3', 'D1_SC1_SSC3_OPT3', 'Moyenne', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Sponsor avec capacité financière limitée ou dépendante de la conjoncture."}'),
  ('D1_SC1_SSC3', 'D1_SC1_SSC3_OPT4', 'Fragile', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Sponsor présentant une tension financière ou une capacité de soutien incertaine."}'),
  ('D1_SC2_SSC1', 'D1_SC2_SSC1_OPT1', 'Structure claire et équilibrée', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Actionnariat stable avec sponsor de référence clairement identifié et capacité de décision."}'),
  ('D1_SC2_SSC1', 'D1_SC2_SSC1_OPT2', 'Structure acceptable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Actionnariat lisible avec gouvernance globalement claire."}'),
  ('D1_SC2_SSC1', 'D1_SC2_SSC1_OPT3', 'Structure complexe', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Actionnariat dispersé ou avec plusieurs intérêts pouvant ralentir la décision."}'),
  ('D1_SC2_SSC1', 'D1_SC2_SSC1_OPT4', 'Structure opaque', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Actionnariat peu transparent ou difficile à contrôler."}'),
  ('D1_SC2_SSC2', 'D1_SC2_SSC2_OPT1', 'Alignement fort', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Les actionnaires ont des intérêts économiques convergents et restent engagés sur la durée."}'),
  ('D1_SC2_SSC2', 'D1_SC2_SSC2_OPT2', 'Alignement correct', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Les intérêts sont globalement alignés avec quelques clauses à renforcer."}'),
  ('D1_SC2_SSC2', 'D1_SC2_SSC2_OPT3', 'Alignement partiel', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Certains actionnaires peuvent avoir des objectifs divergents."}'),
  ('D1_SC2_SSC2', 'D1_SC2_SSC2_OPT4', 'Alignement faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Risque d’abandon ou de désengagement d’un actionnaire clé."}'),
  ('D1_SC2_SSC3', 'D1_SC2_SSC3_OPT1', 'Engagement ferme', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Sponsor engagé jusqu’à maturité ou période longue avec support contractuel."}'),
  ('D1_SC2_SSC3', 'D1_SC2_SSC3_OPT2', 'Engagement satisfaisant', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Engagement prévu sur une période suffisante pour sécuriser le projet."}'),
  ('D1_SC2_SSC3', 'D1_SC2_SSC3_OPT3', 'Engagement limité', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Engagement temporel ou financier insuffisant pour absorber les aléas."}'),
  ('D1_SC2_SSC3', 'D1_SC2_SSC3_OPT4', 'Engagement absent', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Sponsor opportuniste ou absence d’obligation de soutien."}'),
  ('D1_SC3_SSC1', 'D1_SC3_SSC1_OPT1', 'Gouvernance robuste', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Organes de décision clairs, comités définis, séparation des rôles."}'),
  ('D1_SC3_SSC1', 'D1_SC3_SSC1_OPT2', 'Gouvernance correcte', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Structure de gouvernance présente mais perfectible."}'),
  ('D1_SC3_SSC1', 'D1_SC3_SSC1_OPT3', 'Gouvernance faible', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Décisions centralisées ou responsabilités insuffisamment formalisées."}'),
  ('D1_SC3_SSC1', 'D1_SC3_SSC1_OPT4', 'Gouvernance opaque', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Absence de gouvernance claire ou forte concentration du pouvoir."}'),
  ('D1_SC3_SSC2', 'D1_SC3_SSC2_OPT1', 'Très transparente', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Informations fiables, auditées, accessibles et cohérentes."}'),
  ('D1_SC3_SSC2', 'D1_SC3_SSC2_OPT2', 'Bonne transparence', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Information suffisante avec quelques compléments mineurs."}'),
  ('D1_SC3_SSC2', 'D1_SC3_SSC2_OPT3', 'Transparence moyenne', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Informations partielles ou retards de transmission."}'),
  ('D1_SC3_SSC2', 'D1_SC3_SSC2_OPT4', 'Transparence faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Information insuffisante ou non fiable."}'),
  ('D1_SC3_SSC3', 'D1_SC3_SSC3_OPT1', 'Reporting complet', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Reporting régulier, standardisé et auditable."}'),
  ('D1_SC3_SSC3', 'D1_SC3_SSC3_OPT2', 'Reporting satisfaisant', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Reporting régulier mais avec quelques limites."}'),
  ('D1_SC3_SSC3', 'D1_SC3_SSC3_OPT3', 'Reporting limité', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Reporting peu détaillé ou peu fréquent."}'),
  ('D1_SC3_SSC3', 'D1_SC3_SSC3_OPT4', 'Reporting absent/faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Absence de reporting structuré."}'),
  ('D2_SC1_SSC1', 'D2_SC1_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC1_SSC1', 'D2_SC1_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC1_SSC1', 'D2_SC1_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC1_SSC1', 'D2_SC1_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC1_SSC2', 'D2_SC1_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC1_SSC2', 'D2_SC1_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC1_SSC2', 'D2_SC1_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC1_SSC2', 'D2_SC1_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC1_SSC3', 'D2_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC1_SSC3', 'D2_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC1_SSC3', 'D2_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC1_SSC3', 'D2_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC2_SSC1', 'D2_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC2_SSC1', 'D2_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC2_SSC1', 'D2_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC2_SSC1', 'D2_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC2_SSC2', 'D2_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC2_SSC2', 'D2_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC2_SSC2', 'D2_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC2_SSC2', 'D2_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC2_SSC3', 'D2_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC2_SSC3', 'D2_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC2_SSC3', 'D2_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC2_SSC3', 'D2_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC3_SSC1', 'D2_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC3_SSC1', 'D2_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC3_SSC1', 'D2_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC3_SSC1', 'D2_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC3_SSC2', 'D2_SC3_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC3_SSC2', 'D2_SC3_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC3_SSC2', 'D2_SC3_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC3_SSC2', 'D2_SC3_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D2_SC3_SSC3', 'D2_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D2_SC3_SSC3', 'D2_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D2_SC3_SSC3', 'D2_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D2_SC3_SSC3', 'D2_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D3_SC1_SSC1', 'D3_SC1_SSC1_OPT1', 'EPC lump sum turnkey', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Contrat clé en main, prix fixe, délai garanti, performance garantie."}'),
  ('D3_SC1_SSC1', 'D3_SC1_SSC1_OPT2', 'Prix ferme ajustements limités', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Contrat globalement sécurisé avec ajustements encadrés."}'),
  ('D3_SC1_SSC1', 'D3_SC1_SSC1_OPT3', 'Prix révisable', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Risque de surcoût partiellement porté par la SPV."}'),
  ('D3_SC1_SSC1', 'D3_SC1_SSC1_OPT4', 'Non forfaitaire/cost plus', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Risque de coût largement porté par le projet."}'),
  ('D3_SC1_SSC2', 'D3_SC1_SSC2_OPT1', 'EPC international majeur', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Constructeur très expérimenté et financièrement solide."}'),
  ('D3_SC1_SSC2', 'D3_SC1_SSC2_OPT2', 'EPC régional solide', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Expérience confirmée dans la région/secteur."}'),
  ('D3_SC1_SSC2', 'D3_SC1_SSC2_OPT3', 'EPC moyen', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Expérience partielle ou taille limitée."}'),
  ('D3_SC1_SSC2', 'D3_SC1_SSC2_OPT4', 'EPC faible/nouveau', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Faible expérience ou fragilité financière."}'),
  ('D3_SC1_SSC3', 'D3_SC1_SSC3_OPT1', 'Garanties fortes', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "LDs et garanties couvrent correctement retard/sous-performance."}'),
  ('D3_SC1_SSC3', 'D3_SC1_SSC3_OPT2', 'Garanties correctes', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Garanties présentes mais caps moins élevés."}'),
  ('D3_SC1_SSC3', 'D3_SC1_SSC3_OPT3', 'Garanties faibles', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Garanties limitées ou exclusions importantes."}'),
  ('D3_SC1_SSC3', 'D3_SC1_SSC3_OPT4', 'Absence de garanties', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Aucune protection crédible contre retard/sous-performance."}'),
  ('D3_SC2_SSC1', 'D3_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D3_SC2_SSC1', 'D3_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D3_SC2_SSC1', 'D3_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D3_SC2_SSC1', 'D3_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D3_SC2_SSC2', 'D3_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D3_SC2_SSC2', 'D3_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D3_SC2_SSC2', 'D3_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D3_SC2_SSC2', 'D3_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D3_SC2_SSC3', 'D3_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D3_SC2_SSC3', 'D3_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D3_SC2_SSC3', 'D3_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D3_SC2_SSC3', 'D3_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D3_SC3_SSC1', 'D3_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D3_SC3_SSC1', 'D3_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D3_SC3_SSC1', 'D3_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D3_SC3_SSC1', 'D3_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D3_SC3_SSC2', 'D3_SC3_SSC2_OPT1', 'Couverture très forte', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Assurances/garanties couvrent quasi totalement l’exposition."}'),
  ('D3_SC3_SSC2', 'D3_SC3_SSC2_OPT2', 'Couverture bonne', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Couverture suffisante avec quelques limites."}'),
  ('D3_SC3_SSC2', 'D3_SC3_SSC2_OPT3', 'Couverture partielle', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Couverture insuffisante nécessitant mitigants."}'),
  ('D3_SC3_SSC2', 'D3_SC3_SSC2_OPT4', 'Couverture faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Sous-couverture importante."}'),
  ('D3_SC3_SSC3', 'D3_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D3_SC3_SSC3', 'D3_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D3_SC3_SSC3', 'D3_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D3_SC3_SSC3', 'D3_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC1_SSC1', 'D4_SC1_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC1_SSC1', 'D4_SC1_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC1_SSC1', 'D4_SC1_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC1_SSC1', 'D4_SC1_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC1_SSC2', 'D4_SC1_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC1_SSC2', 'D4_SC1_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC1_SSC2', 'D4_SC1_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC1_SSC2', 'D4_SC1_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC1_SSC3', 'D4_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC1_SSC3', 'D4_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC1_SSC3', 'D4_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC1_SSC3', 'D4_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC2_SSC1', 'D4_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC2_SSC1', 'D4_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC2_SSC1', 'D4_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC2_SSC1', 'D4_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC2_SSC2', 'D4_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC2_SSC2', 'D4_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC2_SSC2', 'D4_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC2_SSC2', 'D4_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC2_SSC3', 'D4_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC2_SSC3', 'D4_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC2_SSC3', 'D4_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC2_SSC3', 'D4_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC3_SSC1', 'D4_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC3_SSC1', 'D4_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC3_SSC1', 'D4_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC3_SSC1', 'D4_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC3_SSC2', 'D4_SC3_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC3_SSC2', 'D4_SC3_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC3_SSC2', 'D4_SC3_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC3_SSC2', 'D4_SC3_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D4_SC3_SSC3', 'D4_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D4_SC3_SSC3', 'D4_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D4_SC3_SSC3', 'D4_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D4_SC3_SSC3', 'D4_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC1_SSC1', 'D5_SC1_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC1_SSC1', 'D5_SC1_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC1_SSC1', 'D5_SC1_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC1_SSC1', 'D5_SC1_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC1_SSC2', 'D5_SC1_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC1_SSC2', 'D5_SC1_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC1_SSC2', 'D5_SC1_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC1_SSC2', 'D5_SC1_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC1_SSC3', 'D5_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC1_SSC3', 'D5_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC1_SSC3', 'D5_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC1_SSC3', 'D5_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC2_SSC1', 'D5_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC2_SSC1', 'D5_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC2_SSC1', 'D5_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC2_SSC1', 'D5_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC2_SSC2', 'D5_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC2_SSC2', 'D5_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC2_SSC2', 'D5_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC2_SSC2', 'D5_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC2_SSC3', 'D5_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC2_SSC3', 'D5_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC2_SSC3', 'D5_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC2_SSC3', 'D5_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}')
  ) AS o(ssc_code, opt_code, opt_label, opt_score, opt_risk, opt_color, opt_order, opt_meta)
  JOIN "BP_PF_v7pp_scoring_nodes" n ON n.code = o.ssc_code AND n."versionId" = v_version_id AND n."nodeType" = 'SUB_SUB_CRITERION';
END $$;