DO $$
DECLARE v_version_id TEXT;
BEGIN
  SELECT id INTO v_version_id FROM "BP_PF_v7pp_scoring_versions" 
  WHERE "modelId" = (SELECT id FROM "BP_PF_v7pp_scoring_models" WHERE code = 'PF_V7PP')
    AND status = 'PUBLISHED' ORDER BY "versionNumber" DESC LIMIT 1;

  INSERT INTO "BP_PF_v7pp_scoring_options" (id, "nodeId", code, label, value, score, "riskLevel", color, "orderIndex", "isDefault", "isActive", "metadataJson", "createdAt", "updatedAt")
  SELECT gen_random_uuid()::TEXT, n.id, o.opt_code, o.opt_label, o.opt_score::TEXT, o.opt_score, o.opt_risk, o.opt_color, o.opt_order, false, true, o.opt_meta, NOW(), NOW()
  FROM (VALUES

  ('D5_SC3_SSC1', 'D5_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC3_SSC1', 'D5_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC3_SSC1', 'D5_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC3_SSC1', 'D5_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC3_SSC2', 'D5_SC3_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC3_SSC2', 'D5_SC3_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC3_SSC2', 'D5_SC3_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC3_SSC2', 'D5_SC3_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D5_SC3_SSC3', 'D5_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D5_SC3_SSC3', 'D5_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D5_SC3_SSC3', 'D5_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D5_SC3_SSC3', 'D5_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC1_SSC1', 'D6_SC1_SSC1_OPT1', 'Investment Grade / souverain fort', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Contrepartie très solvable avec historique impeccable."}'),
  ('D6_SC1_SSC1', 'D6_SC1_SSC1_OPT2', 'Solide', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Contrepartie solvable mais non forcément IG."}'),
  ('D6_SC1_SSC1', 'D6_SC1_SSC1_OPT3', 'Moyenne', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Solvabilité correcte mais vulnérable au cycle."}'),
  ('D6_SC1_SSC1', 'D6_SC1_SSC1_OPT4', 'Fragile', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Risque élevé de non-paiement."}'),
  ('D6_SC1_SSC2', 'D6_SC1_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC1_SSC2', 'D6_SC1_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC1_SSC2', 'D6_SC1_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC1_SSC2', 'D6_SC1_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC1_SSC3', 'D6_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC1_SSC3', 'D6_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC1_SSC3', 'D6_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC1_SSC3', 'D6_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC2_SSC1', 'D6_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC2_SSC1', 'D6_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC2_SSC1', 'D6_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC2_SSC1', 'D6_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC2_SSC2', 'D6_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC2_SSC2', 'D6_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC2_SSC2', 'D6_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC2_SSC2', 'D6_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC2_SSC3', 'D6_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC2_SSC3', 'D6_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC2_SSC3', 'D6_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC2_SSC3', 'D6_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC3_SSC1', 'D6_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC3_SSC1', 'D6_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC3_SSC1', 'D6_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC3_SSC1', 'D6_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC3_SSC2', 'D6_SC3_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC3_SSC2', 'D6_SC3_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC3_SSC2', 'D6_SC3_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC3_SSC2', 'D6_SC3_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D6_SC3_SSC3', 'D6_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D6_SC3_SSC3', 'D6_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D6_SC3_SSC3', 'D6_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D6_SC3_SSC3', 'D6_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D7_SC1_SSC1', 'D7_SC1_SSC1_OPT1', 'Leverage prudent', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Dette/fonds propres conservateur."}'),
  ('D7_SC1_SSC1', 'D7_SC1_SSC1_OPT2', 'Leverage acceptable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Endettement cohérent avec le secteur."}'),
  ('D7_SC1_SSC1', 'D7_SC1_SSC1_OPT3', 'Leverage élevé', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Structure tendue nécessitant protections fortes."}'),
  ('D7_SC1_SSC1', 'D7_SC1_SSC1_OPT4', 'Leverage excessif', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Fonds propres insuffisants."}'),
  ('D7_SC1_SSC2', 'D7_SC1_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D7_SC1_SSC2', 'D7_SC1_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D7_SC1_SSC2', 'D7_SC1_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D7_SC1_SSC2', 'D7_SC1_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D7_SC1_SSC3', 'D7_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D7_SC1_SSC3', 'D7_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D7_SC1_SSC3', 'D7_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D7_SC1_SSC3', 'D7_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D7_SC2_SSC1', 'D7_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D7_SC2_SSC1', 'D7_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D7_SC2_SSC1', 'D7_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D7_SC2_SSC1', 'D7_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D7_SC2_SSC2', 'D7_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D7_SC2_SSC2', 'D7_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D7_SC2_SSC2', 'D7_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D7_SC2_SSC2', 'D7_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D7_SC2_SSC3', 'D7_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D7_SC2_SSC3', 'D7_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D7_SC2_SSC3', 'D7_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D7_SC2_SSC3', 'D7_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D7_SC3_SSC1', 'D7_SC3_SSC1_OPT1', 'Très robuste', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "DSCR confortable en base case et en stress modéré."}'),
  ('D7_SC3_SSC1', 'D7_SC3_SSC1_OPT2', 'Robuste', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Capacité de service de la dette satisfaisante."}'),
  ('D7_SC3_SSC1', 'D7_SC3_SSC1_OPT3', 'Limité', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Marge de sécurité faible ; sensibilité importante."}'),
  ('D7_SC3_SSC1', 'D7_SC3_SSC1_OPT4', 'Critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Projet insuffisamment couvert par les flux."}'),
  ('D7_SC3_SSC2', 'D7_SC3_SSC2_OPT1', 'Très robuste', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Couverture long terme très confortable."}'),
  ('D7_SC3_SSC2', 'D7_SC3_SSC2_OPT2', 'Robuste', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Couverture long terme correcte."}'),
  ('D7_SC3_SSC2', 'D7_SC3_SSC2_OPT3', 'Moyen', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Couverture long terme faible."}'),
  ('D7_SC3_SSC2', 'D7_SC3_SSC2_OPT4', 'Faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Capacité long terme insuffisante."}'),
  ('D7_SC3_SSC3', 'D7_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D7_SC3_SSC3', 'D7_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D7_SC3_SSC3', 'D7_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D7_SC3_SSC3', 'D7_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC1_SSC1', 'D8_SC1_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC1_SSC1', 'D8_SC1_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC1_SSC1', 'D8_SC1_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC1_SSC1', 'D8_SC1_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC1_SSC2', 'D8_SC1_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC1_SSC2', 'D8_SC1_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC1_SSC2', 'D8_SC1_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC1_SSC2', 'D8_SC1_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC1_SSC3', 'D8_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC1_SSC3', 'D8_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC1_SSC3', 'D8_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC1_SSC3', 'D8_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC2_SSC1', 'D8_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC2_SSC1', 'D8_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC2_SSC1', 'D8_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC2_SSC1', 'D8_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC2_SSC2', 'D8_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC2_SSC2', 'D8_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC2_SSC2', 'D8_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC2_SSC2', 'D8_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC2_SSC3', 'D8_SC2_SSC3_OPT1', 'Couverture très forte', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Assurances/garanties couvrent quasi totalement l’exposition."}'),
  ('D8_SC2_SSC3', 'D8_SC2_SSC3_OPT2', 'Couverture bonne', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Couverture suffisante avec quelques limites."}'),
  ('D8_SC2_SSC3', 'D8_SC2_SSC3_OPT3', 'Couverture partielle', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Couverture insuffisante nécessitant mitigants."}'),
  ('D8_SC2_SSC3', 'D8_SC2_SSC3_OPT4', 'Couverture faible', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Sous-couverture importante."}'),
  ('D8_SC3_SSC1', 'D8_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC3_SSC1', 'D8_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC3_SSC1', 'D8_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC3_SSC1', 'D8_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D8_SC3_SSC2', 'D8_SC3_SSC2_OPT1', 'Conformité complète', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Toutes les autorisations et exigences sont obtenues sans réserve majeure."}'),
  ('D8_SC3_SSC2', 'D8_SC3_SSC2_OPT2', 'Conformité quasi complète', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Quelques réserves mineures non bloquantes."}'),
  ('D8_SC3_SSC2', 'D8_SC3_SSC2_OPT3', 'Conformité partielle', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Autorisations ou obligations importantes encore en cours."}'),
  ('D8_SC3_SSC2', 'D8_SC3_SSC2_OPT4', 'Non conformité/absence critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Autorisation critique manquante ou non-conformité majeure."}'),
  ('D8_SC3_SSC3', 'D8_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D8_SC3_SSC3', 'D8_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D8_SC3_SSC3', 'D8_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D8_SC3_SSC3', 'D8_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC1_SSC1', 'D9_SC1_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC1_SSC1', 'D9_SC1_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC1_SSC1', 'D9_SC1_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC1_SSC1', 'D9_SC1_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC1_SSC2', 'D9_SC1_SSC2_OPT1', 'Conformité complète', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Toutes les autorisations et exigences sont obtenues sans réserve majeure."}'),
  ('D9_SC1_SSC2', 'D9_SC1_SSC2_OPT2', 'Conformité quasi complète', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Quelques réserves mineures non bloquantes."}'),
  ('D9_SC1_SSC2', 'D9_SC1_SSC2_OPT3', 'Conformité partielle', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Autorisations ou obligations importantes encore en cours."}'),
  ('D9_SC1_SSC2', 'D9_SC1_SSC2_OPT4', 'Non conformité/absence critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Autorisation critique manquante ou non-conformité majeure."}'),
  ('D9_SC1_SSC3', 'D9_SC1_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC1_SSC3', 'D9_SC1_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC1_SSC3', 'D9_SC1_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC1_SSC3', 'D9_SC1_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC2_SSC1', 'D9_SC2_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC2_SSC1', 'D9_SC2_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC2_SSC1', 'D9_SC2_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC2_SSC1', 'D9_SC2_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC2_SSC2', 'D9_SC2_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC2_SSC2', 'D9_SC2_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC2_SSC2', 'D9_SC2_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC2_SSC2', 'D9_SC2_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC2_SSC3', 'D9_SC2_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC2_SSC3', 'D9_SC2_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC2_SSC3', 'D9_SC2_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC2_SSC3', 'D9_SC2_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC3_SSC1', 'D9_SC3_SSC1_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC3_SSC1', 'D9_SC3_SSC1_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC3_SSC1', 'D9_SC3_SSC1_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC3_SSC1', 'D9_SC3_SSC1_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC3_SSC2', 'D9_SC3_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC3_SSC2', 'D9_SC3_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC3_SSC2', 'D9_SC3_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC3_SSC2', 'D9_SC3_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC3_SSC3', 'D9_SC3_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC3_SSC3', 'D9_SC3_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC3_SSC3', 'D9_SC3_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC3_SSC3', 'D9_SC3_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC4_SSC1', 'D9_SC4_SSC1_OPT1', 'Faible exposition', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Site peu exposé aux aléas climatiques majeurs."}'),
  ('D9_SC4_SSC1', 'D9_SC4_SSC1_OPT2', 'Exposition modérée', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Risques présents mais mitigables techniquement."}'),
  ('D9_SC4_SSC1', 'D9_SC4_SSC1_OPT3', 'Exposition élevée', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Risque climatique significatif nécessitant CAPEX/adaptation."}'),
  ('D9_SC4_SSC1', 'D9_SC4_SSC1_OPT4', 'Exposition critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Risque climatique pouvant compromettre la viabilité."}'),
  ('D9_SC4_SSC2', 'D9_SC4_SSC2_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC4_SSC2', 'D9_SC4_SSC2_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC4_SSC2', 'D9_SC4_SSC2_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC4_SSC2', 'D9_SC4_SSC2_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}'),
  ('D9_SC4_SSC3', 'D9_SC4_SSC3_OPT1', 'Niveau très favorable', 10.0, 'TRES_FAIBLE', '#15803d', 1, '{"when_choose": "Choisir lorsque le sous-sous-critère présente une robustesse élevée, documentée et validée par des sources indépendantes."}'),
  ('D9_SC4_SSC3', 'D9_SC4_SSC3_OPT2', 'Niveau favorable', 8.0, 'FAIBLE', '#86efac', 2, '{"when_choose": "Choisir lorsque le risque est maîtrisé avec quelques points d’amélioration mineurs."}'),
  ('D9_SC4_SSC3', 'D9_SC4_SSC3_OPT3', 'Niveau moyen / vigilance', 5.0, 'MOYEN', '#fbbf24', 3, '{"when_choose": "Choisir lorsque le risque est partiellement maîtrisé et nécessite des conditions ou mitigants."}'),
  ('D9_SC4_SSC3', 'D9_SC4_SSC3_OPT4', 'Niveau défavorable / critique', 2.0, 'ELEVE', '#dc2626', 4, '{"when_choose": "Choisir lorsque le risque est élevé, peu documenté ou susceptible d’impacter la viabilité du projet."}')
  ) AS o(ssc_code, opt_code, opt_label, opt_score, opt_risk, opt_color, opt_order, opt_meta)
  JOIN "BP_PF_v7pp_scoring_nodes" n ON n.code = o.ssc_code AND n."versionId" = v_version_id AND n."nodeType" = 'SUB_SUB_CRITERION';
END $$;